### ISSUE TITLE
Do you have the plan to add search module?

### ISSUE THREAD

**Issue by panxiaoguang** [nurRiyad/nuxt-blog#11]
Your blog framework is great and I like it very much. But it really needs a search method!

In addition, The blog list page also needs a pagination as the number of blogs will increase more and more.

**Comment by nurRiyad** [comment]
Thanks for bringing up this new feature idea. I will work on it as soon as possible.

**Comment by panxiaoguang** [comment]
Thank you very much. My poor knowledge of Nuxtjs limited my passion for contribution. Your codes are also a good demo for me to learn that. Thanks again for your good job!

**Comment by nurRiyad** [comment]
Hi, I am added both search module and paginations.

**Comment by panxiaoguang** [comment]
> Hi, I am added both search module and paginations.

Yes, I saw it. You are so efficient and awesome! By the way, this is my own blog built using your project! [晓寒月色](https://www.xiaohanyuese.top/), That's a Chinese live demo!

**Comment by nurRiyad** [comment]
Just saw your site It's looking awesome. 👌👌
