### ISSUE TITLE
how to change home title?

### ISSUE THREAD

**Issue by jujutsucode** [nurRiyad/nuxt-blog#53]
i want to change home title
![Screenshot_1](https://github.com/nurRiyad/nuxt-blog/assets/138183266/9ffaf99e-f20b-44ee-a658-f00ed6c95f3d)

**Comment by nurRiyad** [comment]
You need to update here https://github.com/nurRiyad/nuxt-blog/blob/fa2f23f6fa1bae2b968c08c58723205fc9963d39/pages/index.vue#L11

**Comment by jujutsucode** [comment]
i have changed it but the display title still riyads blog
```
<script lang="ts" setup>
useHead({
  title: 'Home',
  meta: [
    {
      name: 'description',
      content:
        'Jasa Pembuatan aplikasi web yang modern dengan Nuxt di Yogyakarta.',
    },
  ],
  titleTemplate: 'Kawan Hosting site - %s',
})

// Generate OG Image
defineOgImageComponent('About', {
  headline: 'Greetings 👋',
  title: 'Kawan Hosting site',
  description: 'Jasa Pembuatan aplikasi web yang modern dengan Nuxt di Yogyakarta.',
  link: '/logo.png',
})
</script>
```

**Comment by jujutsucode** [comment]
you can take alook at kawanhosting.com

**Comment by jujutsucode** [comment]
ok thank you

**Comment by nurRiyad** [comment]
The this title will be update from the `navbarData.homeTitle`
