### ISSUE TITLE
Fix mobile design issue

### ISSUE THREAD

**Issue by nurRiyad** [nurRiyad/nuxt-blog#57]

**Comment by abidta** [comment]
what is the issue

**Comment by nurRiyad** [comment]
![Screenshot from 2024-06-27 17-32-29](https://github.com/nurRiyad/nuxt-blog/assets/45213090/f4a5d79d-aacf-4c4a-989f-8480ed7c444a)
![Screenshot from 2024-06-27 17-32-18](https://github.com/nurRiyad/nuxt-blog/assets/45213090/a8738fcf-fe09-4c1e-996e-98011bea9e72)

**Comment by nurRiyad** [comment]
Recently I have added the share option in the blogs page. But I didn't make it mobile responsive. Need to make it mobile responsive. So that the line properly break when needed.

**Comment by nurRiyad** [comment]
Fixed #58
