### ISSUE TITLE
m1,m2编译后图片无法加载

### ISSUE THREAD

**Issue by cc158999** [nurRiyad/nuxt-blog#67]
报错：
{
    "error": {
        "message": "[500] [IPX_ERROR] Could not load the \"sharp\" module using the darwin-arm64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=darwin --cpu=arm64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install"
    }
}

这个错误信息表明在运行时无法加载 sharp 模块，这是一个用于处理图像的高性能库。该错误通常发生在你的开发环境或生产环境与 sharp 模块编译时的目标架构不匹配的情况下，尤其是在使用苹果芯片（darwin-arm64）的设备上，如 M1 或 M2 芯片的 Mac。

**Comment by nurRiyad** [comment]
@cc158999  Can you share your node & npm version ? because I am also using m2 pro but in my pc it's working file.

**Comment by cc158999** [comment]
好的，npm：10.7.0。node：v20.15.1

**Comment by cc158999** [comment]
<img width="1421" alt="截屏2024-08-16 下午6 21 47" src="https://github.com/user-attachments/assets/15626b41-a148-4ddd-b33c-f48c743377b6">
<img width="1436" alt="截屏2024-08-16 下午6 21 54" src="https://github.com/user-attachments/assets/bd204142-9d1d-4899-96bb-8fd7ad51f7e7">

yarn run dev和yarn run build编译后这些图片都加载不出来。我的环境是npm:10.7.0，node:v20.15.1，yarn:v1.22.22。使用的m1处理器。谢谢🙏

**Comment by cc158999** [comment]
yarn run build时候的报错信息：

[nitro 18:26:32]   ├─ /_payload.json?363a46a9-5766-449d-97ac-09a57b808c7a (22ms) (skipped)
  ├─ /_payload.json (2ms)                                       nitro 18:26:32
  ├─ /_ipx/w_300/blogs-img/blog6.jpg (57ms)                     nitro 18:26:32
  │ ├── Error: [500] 
  │ └── Linked from /
  ├─ /_ipx/w_600/blogs-img/blog6.jpg (55ms)                     nitro 18:26:32
  │ ├── Error: [500] 
  │ └── Linked from /
  ├─ /about (52ms)                                              nitro 18:26:32
[nitro 18:26:32]   ├─ /about/_payload.json?363a46a9-5766-449d-97ac-09a57b808c7a (9ms) (skipped)
  ├─ /api/_content/query/rxNjDaCyIs.1723803984053.json (59ms)   nitro 18:26:32
  ├─ /api/_content/query/vehN2UmQbx.1723803984053.json (61ms)   nitro 18:26:32
  ├─ /_ipx/q_50&s_125x115/logo.png (15ms)                       nitro 18:26:32
  │ ├── Error: [500] 
  │ └── Linked from /about
  ├─ /_ipx/q_50&s_250x230/logo.png (15ms)                       nitro 18:26:32
  │ ├── Error: [500] 
  │ └── Linked from /about
  ├─ /_ipx/q_50&s_900x1000/logo.png (13ms)                      nitro 18:26:32
  │ ├── Error: [500] 
  │ └── Linked from /about
  ├─ /about/_payload.json (3ms)                                 nitro 18:26:32
  ├─ /_ipx/q_50&s_450x500/logo.png (17ms)                       nitro 18:26:32
  │ ├── Error: [500] 
  │ └── Linked from /about
  ├─ /blogs/connect-namecheap-to-vercel (94ms)                  nitro 18:26:32
[nitro 18:26:32]   ├─ /blogs/connect-namecheap-to-vercel/_payload.json?363a46a9-5766-449d-97ac-09a57b808c7a (7ms) (skipped)
  ├─ /categories (119ms)                                        nitro 18:26:32
  ├─ /_ipx/w_1200/blogs-img/blog6.jpg (11ms)                    nitro 18:26:32
  │ ├── Error: [500] 
  │ └── Linked from /blogs/connect-namecheap-to-vercel
[nitro 18:26:32]   ├─ /categories/_payload.json?363a46a9-5766-449d-97ac-09a57b808c7a (8ms) (skipped)
  ├─ /api/_content/query/aR1EAj2GAa.1723803984053.json (6ms)    nitro 18:26:32
  ├─ /blogs/connect-namecheap-to-vercel/_payload.json (3ms)     nitro 18:26:32
  ├─ /__og-image__/image/og.png (114ms)                         nitro 18:26:32
  ├─ /__og-image__/image/about/og.png (53ms)                    nitro 18:26:32
  ├─ /categories/_payload.json (4ms)                            nitro 18:26:32
[nitro 18:26:32]   ├─ /__og-image__/image/blogs/connect-namecheap-to-vercel/og.png (9ms)
  ├─ /__og-image__/image/categories/og.png (14ms)               nitro 18:26:32
  ├─ /api/_content/query/KC22hs8gpF.1723803984053.json (18ms)   nitro 18:26:32
  ├─ /categories/namecheap (25ms)                               nitro 18:26:32
  ├─ /categories/vercel (27ms)                                  nitro 18:26:32
[nitro 18:26:32]   ├─ /categories/namecheap/_payload.json?363a46a9-5766-449d-97ac-09a57b808c7a (3ms) (skipped)
[nitro 18:26:32]   ├─ /categories/vercel/_payload.json?363a46a9-5766-449d-97ac-09a57b808c7a (3ms) (skipped)
  ├─ /categories/namecheap/_payload.json (1ms)                  nitro 18:26:32
  ├─ /categories/vercel/_payload.json (1ms)                     nitro 18:26:32
  ├─ /__og-image__/image/categories/namecheap/og.png (7ms)      nitro 18:26:32
  ├─ /__og-image__/image/categories/vercel/og.png (14ms)        nitro 18:26:32
  ├─ /api/_content/query/TLOvm1p6Mh.1723803984053.json (21ms)   nitro 18:26:32
  ├─ /api/_content/query/hgdgSmNKvh.1723803984053.json (17ms)   nitro 18:26:32
  ├─ /blogs (334ms)                                             nitro 18:26:32
[nitro 18:26:32]   ├─ /blogs/_payload.json?363a46a9-5766-449d-97ac-09a57b808c7a (5ms) (skipped)
  ├─ /blogs/_payload.json (3ms)                                 nitro 18:26:32
  ├─ /__og-image__/image/blogs/og.png (7ms)                     nitro 18:26:32
                                                                nitro 18:26:34
Errors prerendering:
  ├─ /_ipx/w_300/blogs-img/blog6.jpg (57ms)                     nitro 18:26:34
  │ ├── Error: [500] 
  │ └── Linked from /
  │ └── Linked from /categories/namecheap
  │ └── Linked from /categories/vercel
  ├─ /_ipx/w_600/blogs-img/blog6.jpg (55ms)                     nitro 18:26:34
  │ ├── Error: [500] 
  │ └── Linked from /
  │ └── Linked from /blogs/connect-namecheap-to-vercel
  │ └── Linked from /categories/namecheap
  │ └── Linked from /categories/vercel
  ├─ /_ipx/q_50&s_125x115/logo.png (15ms)                       nitro 18:26:34
  │ ├── Error: [500] 
  │ └── Linked from /about
  ├─ /_ipx/q_50&s_250x230/logo.png (15ms)                       nitro 18:26:34
  │ ├── Error: [500] 
  │ └── Linked from /about
  ├─ /_ipx/q_50&s_900x1000/logo.png (13ms)                      nitro 18:26:34
  │ ├── Error: [500] 
  │ └── Linked from /about
  ├─ /_ipx/q_50&s_450x500/logo.png (17ms)                       nitro 18:26:34
  │ ├── Error: [500] 
  │ └── Linked from /about
  ├─ /_ipx/w_1200/blogs-img/blog6.jpg (11ms)                    nitro 18:26:34
  │ ├── Error: [500] 
  │ └── Linked from /blogs/connect-namecheap-to-vercel
                                                                nitro 18:26:34

 ERROR  Exiting due to prerender errors.                              18:26:34

  at prerender (node_modules/nitropack/dist/chunks/prerender.mjs:218:11)
  at async node_modules/nuxt/dist/index.mjs:3540:7
  at async build (node_modules/nuxt/dist/index.mjs:5333:5)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:94:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1777:7) 



 ERROR  Exiting due to prerender errors.                              18:26:34

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
aifeng@aifengdeMacBook-Pro nuxt-blog-1.3.0 %

**Comment by nurRiyad** [comment]
Give me some hours. Hopefully I will fix the issue

**Comment by cc158999** [comment]
ok 非常感谢你的帮助

**Comment by nurRiyad** [comment]
I have checked my master branch with both npm and yarn. It's build fine and working fine. I think the issue is with your changes.

**Comment by cc158999** [comment]
抱歉，您的构建是良好的，是我更改导致了报错。已经解决了
