### ISSUE TITLE
Unnable to deploy on Cloudflare pages

### ISSUE THREAD

**Issue by MAbarri** [nurRiyad/nuxt-blog#68]
Your work is very clean and nice, great template to work with, 

I am trying to deploy to cloudflare pages, the worker size results more than 1MBit

would you be able to minimize the project size to be deployable on cloudflare pages ? i removed every article and every image from the project and that seems not to be the problem, i think the dependencies are making the project heavier than it should be ?
<img width="749" alt="Screenshot 2024-09-01 at 18 59 08" src="https://github.com/user-attachments/assets/33d61990-aacb-44d2-ae0a-41875f40e474">

Thanks

**Comment by nurRiyad** [comment]
It's `nuxt-og-image`
https://nuxtseo.com/nuxt-seo/guides/using-the-modules#keeping-workers-under-1mb

**Comment by MAbarri** [comment]
Thank you

I added in nuxt.config.ts the following : 

`
  ogImage: {
    enabled: false
  },
`

And it works like charm,

thanks
